NewsPaper/NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
   path('i18n/', include('django.conf.urls.i18n')),
   path('admin/', admin.site.urls),
   path('pages/', include('django.contrib.flatpages.urls')),
   path("accounts/", include("allauth.urls")),
   path('', include('accounts.urls'))
]

NewsPaper/accounts/urls.py
from django.urls import path
from .views import NewsList, NewsDetail, Search, PostCreate, PostEdit, PostDelete, SignUp, subscriptions
from django.views.decorators.cache import cache_page

urlpatterns = [
   path('news/', cache_page(60)(NewsList.as_view()), name='news_list'),
   path('news/<int:pk>', cache_page(60*5)(NewsDetail.as_view())),
   path('news/search/', Search.as_view()),
   path('news/create/', PostCreate.as_view(), name='post_create'),
   path('news/<int:pk>/edit/', PostEdit.as_view(), name='post_edit'),
   path('news/<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
   path('signup', SignUp.as_view(), name='signup'),
   path('subscriptions/', subscriptions, name='subscriptions'),
]

NewsPaper/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse
from django.core.cache import cache
from django.utils.translation import gettext as _
from django.utils.translation import pgettext_lazy


class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    ratingAuthor = models.SmallIntegerField(default=0)

    def update_rating(self):
        postRat = self.post_set.aggregate(postRating=Sum('rating'))
        pRat = 0
        pRat += postRat.get('postRating')

        commentRat = self.authorUser.comment_set.aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += commentRat.get('commentRating')

        self.ratingAuthor = pRat * 3 + cRat
        self.save()

    def __str__(self):
        return f'{self.authorUser}'


class Category(models.Model):
    name = models.CharField(max_length=64, unique=True, help_text=_('category name'))

    def __str__(self):
        return f'{self.name}'


class MyModel(models.Model):
    name = models.CharField(max_length=100)
    kind = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name='kinds',
        verbose_name=pgettext_lazy('help text for MyModel model', 'This is the help text'),
    )


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOISES = (
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья')
    )
    categoryType = models.CharField(max_length=2, choices=CATEGORY_CHOISES, default=ARTICLE)
    dateCreation = models.DateTimeField(auto_now_add=True)
    postCategory = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=128)
    text = models.TextField()
    rating = models.SmallIntegerField(default=0)

    def __str__(self):
        return f'{self.title}'

    def get_absolute_url(self):
        return f'/products/{self.id}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        cache.delete(f'product-{self.pk}')

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return '{} ... {}'.format(self.text[0:123], str(self.rating))


class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    dateCreation = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def __str__(self):
        return f'{self.text}'


class Subscriber(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )

    def __str__(self):
        return f'{self.user}'

NewsPaper/templates/category_list.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
Новости
{% endblock title %}

{% block content %}
<h1>{% trans "Number of news per page" %}: {{ news|length }}</h1>

    {% if is_not_subscriber %}
        <p class="text-center"><a href="{}" class="btn btn-secondary btn-sm">{% trans "Subscribe" %}</a></p>
    {% endif %}


    {% if perms.accounts.add_post %}
    <a href="{% url 'post_create' %}">{% trans "Add post" %}</a>
    {% endif %}

<hr>
    {% if news %}
        <table>
            <tr>
                <td>{% trans "Title" %}</td>
                <td>{% trans "Publication date" %}</td>
                <td>{% trans "Text" %}</td>
                {% if perms.accounts.change_post or perms.accounts.delete_post %}
                <td>{% trans "Actions" %}</td>
                {% endif %}

            </tr>

            {% for news_detail in news %}
            <tr>
                <td>{{ news_detail.title|censor }}</td>
                <td>{{ news_detail.dateCreation|date:'d M Y' }}</td>
                <td>{{ news_detail.text|truncatewords:20 }}</td>

                <td>
                    {% if perms.accounts.change_post %}
                    <a href="{% url 'post_edit' news_detail.id %}">{% trans "Edit" %}</a>
                    {% endif %}
                    {% if perms.accounts.delete_post %}
                    <a href="{% url 'post_delete' news_detail.id %}">{% trans "Delete" %}</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}

        </table>
    {% else %}
        <h2>{% trans "No news" %}</h2>
    {% endif %}

   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

NewsPaper/templates/daily_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>{% trans "Hello! New articles for the last week" %}:</h2>>
<ul>
  {% for post in posts %}
    <li><a href="{{ link }}{{ post.get_absolute_url }}">{{ post.title }}</a></li>
  {% endfor %}
</ul>
</body>
</html>

NewsPaper/templates/news.html
{% extends 'flatpages/default.html' %}

{% load i18n %}

{% load custom_filters %}

{% block title %}
News
{% endblock title %}

{% block content %}
<h1>{% trans "Number of news per page" %}: {{ news|length }}</h1>

{% load cache %}
    {% cache 30 add_news %}
        {% if perms.accounts.add_post %}
        <a href="{% url 'post_create' %}">{% trans "Add post" %}</a>
        {% endif %}
    {% endcache %}
<hr>
    {% if news %}
        <table>
            <tr>
                <td>{% trans "Title" %}</td>
                <td>{% trans "Publication date" %}</td>
                <td>{% trans "Text" %}</td>
                {% if perms.accounts.change_post or perms.accounts.delete_post %}
                <td>{% trans "Actions" %}</td>
                {% endif %}

            </tr>

            {% for news_detail in news %}
            <tr>
                <td>{{ news_detail.title|censor }}</td>
                <td>{{ news_detail.dateCreation|date:'d M Y' }}</td>
                <td>{{ news_detail.text|truncatewords:20 }}</td>

                <td>
                    {% if perms.accounts.change_post %}
                    <a href="{% url 'post_edit' news_detail.id %}">{% trans "Edit" %}</a>
                    {% endif %}
                    {% if perms.accounts.delete_post %}
                    <a href="{% url 'post_delete' news_detail.id %}">{% trans "Delete" %}</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}

        </table>
    {% else %}
        <h2>{% trans "No news" %}</h2>
    {% endif %}

           {% if page_obj.has_previous %}
               <a href="?page=1">1</a>
               {% if page_obj.previous_page_number != 1 %}
                   ...
                   <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
               {% endif %}
           {% endif %}

           {{ page_obj.number }}

           {% if page_obj.has_next %}
               <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
               {% if paginator.num_pages != page_obj.next_page_number %}
                   ...
                   <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
               {% endif %}
           {% endif %}

{% endblock content %}

NewsPaper/templates/news_detail.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
{% trans "News detail" %}
{% endblock title %}

{% block content %}
<h1>{{ news_detail.title|censor }}</h1>
<h2>{{ news_detail.dateCreation|date:'d M Y' }}</h2>
{{ news_detail.text|censor }}

{% endblock content %}

NewsPaper/templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>{% trans "Delete news" %}</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>{% trans "Do you want to delete a post" %} "{{ post.title }}"?</p>
    <input type="submit" value="Удалить" />
</form>
{% endblock content %}

NewsPaper/templates/post_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>{% trans "Post" %}</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPaper/templates/search.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
{% trans "Search" %}
{% endblock title %}

{% block content %}

    <form action="" method="get">
        {{ filterset.form.as_p }}
        <input type="submit" value="Найти" />
    </form>

<hr>
    {% if news %}
        <table>
            <tr>
                <td>{% trans "Title" %}</td>
                <td>{% trans "Publication date" %}</td>
                <td>{% trans "Text" %}</td>
            </tr>

            {% for news_detail in news %}
            <tr>
                <td>{{ news_detail.title|censor }}</td>
                <td>{{ news_detail.dateCreation|date:'d M Y' }}</td>
                <td>{{ news_detail.text|truncatewords:20 }}</td>
            </tr>
            {% endfor %}

        </table>
    {% else %}
        <h2>{% trans "No news" %}</h2>
    {% endif %}

   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

NewsPaper/templates/subscriptions.html
{% extends 'flatpages/default.html' %}

{% block title %}
<h2>{% trans "Subscribtions" %}</h2>
{% endblock title %}

{% block content %}
    {% for category in categories  %}
        <p>
            {{ category.name }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />
                    {% if category.user_subscribed %}
                        <button disabled><h2>{% trans "Subscribe" %}</h2></button>
                        <button name="action" value="unsubscribe"><h2>{% trans "Unsubscribe" %}</h2></button>
                    {% else %}
                        <button name="action" value="subscribe">{% trans "Subscribe" %}</button>
                        <button disabled>{% trans "Unsubscribe" %}</button>
                    {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}